# Generated by Django 4.2.3 on 2023-08-18 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_rest', '0003_produk_diskon_aktif_produk_produk_diskon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoppingCart',
            fields=[
                ('username_cart', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('kode_produk', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_rest.produk')),
            ],
        ),
    ]
