# Generated by Django 4.2.3 on 2023-08-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0002_shoppingcart_id_alter_shoppingcart_username_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='id',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='username_cart',
            field=models.CharField(default=None, max_length=200, primary_key=True, serialize=False),
        ),
    ]
