# Generated by Django 4.2.3 on 2023-08-27 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_produk_diskon_aktif_produk_produk_diskon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penjualan', '0006_shoppingcart_id_alter_shoppingcart_username_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='whishlistCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk_whishlist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_rest.produk', verbose_name='Kode Produk')),
                ('username_wishlist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
