# Generated by Django 4.2.3 on 2023-08-27 05:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_produk_diskon_aktif_produk_produk_diskon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penjualan', '0007_whishlistcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whishlistcart',
            old_name='kode_produk_whishlist',
            new_name='kode_produk_wishlist',
        ),
        migrations.AlterUniqueTogether(
            name='whishlistcart',
            unique_together={('username_wishlist', 'kode_produk_wishlist')},
        ),
    ]
