# Generated by Django 4.2.3 on 2023-08-27 05:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_rest', '0003_produk_diskon_aktif_produk_produk_diskon_and_more'),
        ('penjualan', '0008_rename_kode_produk_whishlist_whishlistcart_kode_produk_wishlist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whishlistCart',
            new_name='wishlistCart',
        ),
    ]
