# Generated by Django 4.2.3 on 2023-08-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0009_rename_whishlistcart_wishlistcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total_harga',
            field=models.BigIntegerField(default=0),
        ),
    ]
