# Generated by Django 4.2.3 on 2023-08-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0010_shoppingcart_total_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='harganya',
            field=models.BigIntegerField(default=0),
        ),
    ]
