# Generated by Django 4.2.3 on 2023-08-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0011_shoppingcart_harganya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='harganya',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
