# Generated by Django 4.2.3 on 2023-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('produk_kode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('produk_nama', models.CharField(default='', max_length=200)),
                ('produk_harga', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
