# Generated by Django 4.2.3 on 2023-08-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar1',
            field=models.ImageField(blank=True, null=True, upload_to='gbr_produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar2',
            field=models.ImageField(blank=True, null=True, upload_to='gbr_produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar3',
            field=models.ImageField(blank=True, null=True, upload_to='gbr_produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar4',
            field=models.ImageField(blank=True, null=True, upload_to='gbr_produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar5',
            field=models.ImageField(blank=True, null=True, upload_to='gbr_produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar6',
            field=models.ImageField(blank=True, null=True, upload_to='gbr_produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar7',
            field=models.ImageField(blank=True, null=True, upload_to='gbr_produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar8',
            field=models.ImageField(blank=True, null=True, upload_to='gbr_produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='produk_deskripsi',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
